AWSTemplateFormatVersion: 2010-09-09
Description: Build template to upload model and dependencies

Parameters:
  BucketName:
    Type: String
    Description: The bucket to be created and use to upload the model

Resources:
  DeploymentArtifactBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: Private
      BucketName: !Ref BucketName
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - codebuild.amazonaws.com
  NeoCompilationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: NeoCompilationRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - sagemaker.amazonaws.com
                
  NeoCompilationPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: NeoCompilation
      Roles:
        - !Ref NeoCompilationRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "arn:aws:logs:*:*:*"
          - Effect: Allow
            Action:
              - s3:*
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - sagemaker:*
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - iam:*
            Resource:
              - "*"

  CodeBuildServicePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CodeBuildServicePolicy
      Roles:
        - !Ref CodeBuildServiceRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "arn:aws:logs:*:*:*"
          - Effect: Allow
            Action:
              - s3:*
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - sagemaker:*
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - iam:*
            Resource:
              - "*"

              

  CodeBuildProjectNeo:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: PackageModelNeo
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      LogsConfig : 
        CloudWatchLogs:
          Status: ENABLED
      Environment:
        Type: linuxContainer
        # ComputeType options: BUILD_GENERAL1_SMALL, BUILD_GENERAL1_MEDIUM, BUILD_GENERAL1_LARGE
        ComputeType: BUILD_GENERAL1_SMALL
        # Run `aws codebuild list-curated-environment-images` for a complete list of images provided.
        Image: aws/codebuild/standard:4.0
        EnvironmentVariables:
          - Name: BUILD_ARTIFACT_BUCKET
            Value: !Ref DeploymentArtifactBucket
      Source:
        Type: S3
        Location: !Sub '${BucketName}/codebuild/sagemaker-neo/'
      TimeoutInMinutes: 10
  CodeBuildProjectTFFull:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: PackageModelTFFull
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: linuxContainer
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0
        EnvironmentVariables:
          - Name: BUILD_ARTIFACT_BUCKET
            Value: !Ref DeploymentArtifactBucket
      Source:
        Type: S3
        Location: !Sub '${BucketName}/codebuild/tf_full/'
      TimeoutInMinutes: 10