  
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install tensorflow
  build:
    commands:
      - python build_model.py
      - curl https://storage.googleapis.com/download.tensorflow.org/data/ImageNetLabels.txt -O
      - pip3 install tensorflow -t dependencies
      - mkdir -p model_package
      - mv saved_model ImageNetLabels.txt dependencies model_package
      - tar -zcvf model-package.tar.gz -C model_package .
      - timestampStr=$(date +%y-%m-%d-%H-%M-%S)
      - aws s3 cp model-package.tar.gz s3://${BUILD_ARTIFACT_BUCKET}/models/image-net-tf-full-${timestampStr}/model-package.tar.gz
      - echo "Uploaded final package to s3://${BUILD_ARTIFACT_BUCKET}/models/image-net-tf-full-${timestampStr}/model-package.tar.gz"
    artifacts:
      files:
        - '**/*'
      base-directory: 'model_package'
      
